volumes:
  pg_project:

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - pg_project:/home/bunk3r/test_env/postgresql/data
    ports:
      - 5432:5432

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
      image: redis
      ports:
        - 6379:6379
      environment:
          - ALLOW_EMPTY_PASSWORD=yes
