---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      nodePort: 30300
  selector:
    app: grafana
  type: NodePort
